### DISCUSSION TITLE
Normalization

### DISCUSSION THREAD

**Discussion by FloWsnr** [PolymathicAI/the_well#30] [Q&A] [answered]
Hi guys, thanks for the amazing project.
I am missing some documentation about the field normalization functions inside the ``Dataset`` and ``Dataloader`` classes.
As I understand a yaml file with the layout 

```yaml
mean:
  velocity: 1
  pressure: 7
  density: 88

std:
  velocity: 0.5
  pressure: 1
  density: 0.3
```

must be supplied? Is this the correct layout? How does it treat the t1 and t2 data?

Thank you!

**Comment by rubenohana** [comment]
Hello Florian! 

Thank you for your question! 
The layout you provided is not correct. It should be (you can look at [this example](https://github.com/PolymathicAI/the_well/blob/master/datasets/euler_multi_quadrants_openBC/stats.yaml)): 
```
mean:
  velocity:
  - 1.1 (where this is the value of the first dimension, so in The Well format, for v_x)
  - 2.2 (where this is for v_y)
  pressure: 7
  density: 88

std:
  velocity:
  - 3.1
  - 4.2 
  pressure: 1
  density: 0.3
```
If the field has 1 level with 2 values, it means it is a `t_1` field, and if it has 2 levels (so 4 values, e.g. in [this dataset](https://github.com/PolymathicAI/the_well/blob/master/datasets/active_matter/stats.yaml)) it should be a `t_2` field.

You can use this [script](https://github.com/PolymathicAI/the_well/blob/master/scripts/compute_statistics.py) to compute statistics on any data formatted for the Well.

Let me know if you have more questions!
